
[tools]
bun = "1.3.1"

[env]
'_'.path = ["node_modules/.bin"]

[tasks.install]
run = "mise install & bun install"
wait_for = ["clean"]

[tasks.dev]
run = "eleventy --serve"
description = "Start development server with live reload"
depends = ["clean", "install"]
wait_for = ["clean"]

[tasks.build]
run = "eleventy"
description = "Build the site for production"
depends = ["clean", "install"]
wait_for = ["clean"]

[tasks.clean]
run = "rm -rf _site"
description = "Clean the _site directory"

[tasks.serve]
run = "eleventy --serve"
description = "Build and serve the site locally"
depends = ["install"]
wait_for = ["clean"]
